### ISSUE TITLE
Not able to generate proto when we are adding java-root-package

### ISSUE THREAD

**Issue by Harshitjain1405** [valllabh/ocsf-tool#17]
hjain@138469-P14s:/mnt/c/Users/hjain/downloads/ocsf-tool$ ./ocsf-tool generate-proto file_activity --golang-root-package="stash.intranet.qualys.com/cs/cs-security-events-helper/pkg/generated/" --java-root-package="generated/"
Error: unknown flag: --java-root-package

Not able to generate the proto while adding java-root-package

**Comment by valllabh** [comment]
with v0.1.7, java-root-package is available as a flag read the help for more information
